memory_limit = 256M
upload_max_filesize = 20M
post_max_size = 20M
date.timezone = Europe/Paris

; Opcache : recommandé même en environnement de test pour se rapprocher
; des conditions réelles de production
opcache.enable = 1
opcache.memory_consumption = 128
opcache.max_accelerated_files = 20000
opcache.validate_timestamps = 1
